api_platform:
    title: DEMO PHP API
    version: 1.0.0
    defaults:
        pagination_enabled: false
        pagination_client_enabled: true
        pagination_items_per_page: 100 # Default value
    collection:
        pagination:
            enabled_parameter_name: pagination # optional
    formats:
        jsonld:   ['application/ld+json']
        json:     ['application/json', 'application/merge-patch+json']
        jsonapi:  ['application/vnd.api+json']
        html:     ['text/html']


    exception_to_status:
        # The 4 following handlers are registered by default, keep those lines to prevent unexpected side effects
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400 # Use a raw status code (recommended)
        ApiPlatform\Exception\InvalidArgumentException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_BAD_REQUEST
        ApiPlatform\Exception\FilterValidationException: 400
        Doctrine\ORM\OptimisticLockException: 409

        # Validation exception
        ApiPlatform\Validator\Exception\ValidationException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_UNPROCESSABLE_ENTITY

        # Custom exceptions
        App\Exception\HttpException: 400
        App\Exception\WorkflowException: 400
