# config/filter/country.filter.yaml
services:
    country.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { name: partial, region.id: exact } ]
        tags: [ 'api_platform.filter' ]
    country.order_filter:
        parent: 'api_platform.doctrine.orm.order_filter'
        arguments: [ { id: 'ASC', name: 'ASC', region.name: 'ASC', sortOrder: 'ASC' } ]
        tags: [ 'api_platform.filter' ]