# config/filter/information.filter.yaml
services:
    information.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [{ informationType: 'exact', sortOrder: 'exact', information: 'partial', title: 'partial' }]
        tags:  [ 'api_platform.filter' ]
    information.order_filter:
        parent: 'api_platform.doctrine.orm.order_filter'
        arguments: [{ sortOrder: 'ASC', informationType: 'ASC' }]
        tags: ['api_platform.filter']