# config/filter/region.filter.yaml
services:
    region.order_filter:
        parent: 'api_platform.doctrine.orm.order_filter'
        arguments: [ { id: 'ASC', name: 'ASC', sortOrder: 'ASC' } ]
        tags: [ 'api_platform.filter' ]