# config/serialization/region.serialization.yaml
App\Entity\Region:
    attributes:
        id:
            groups: [ 'Region:read', 'RegionCollection:read', 'Region:write' ]
        name:
            groups: [ 'Region:read', 'RegionCollection:read', 'Region:update' ,'Region:write' ]
        briefDescription:
            groups: [ 'Region:read', 'RegionCollection:read', 'Region:update' ,'Region:write' ]
        shortDescription:
            groups: [ 'Region:read', 'RegionCollection:read', 'Region:update' ,'Region:write' ]
        longDescription:
            groups: [ 'Region:read', 'RegionCollection:read', 'Region:update' ,'Region:write' ]
        active:
            groups: [ 'Region:read', 'RegionCollection:read', 'Region:update' ,'Region:write' ]
        sortOrder:
            groups: [ 'Region:read', 'RegionCollection:read', 'Region:update' ,'Region:write' ]
        createdAt:
            groups: ['Region:read']
        createdBy:
            groups: ['Region:read', 'Region:write']
        updatedAt:
            groups: ['Region:read']
        updatedBy:
            groups: ['Region:read', 'Region:update']
        countries:
            groups: [ 'Region:read' ]
