# config/serialization/user.serialization.yaml
App\Entity\User:
    attributes:
        id:
            groups: [ 'UserCollection:read' ]
        email:
            groups: [ 'User:read', 'UserAccount:read', 'UserCollection:read', 'User:update', 'User:write' ]
        roles:
            groups: [ 'User:read', 'UserCollection:read', 'User:update' ]
        password:
            groups: [ 'User:update', 'UserAccount:update', 'User:write' ]
        currentPassword:
            groups: [ 'UserPassword:update' ]
        newPassword:
            groups: [ 'UserPassword:update' ]
        userId:
            groups: [ 'User:read', 'UserAccount:read', 'UserCollection:read', 'UserPublic:read', 'BlogPost:read']
        title:
            groups: [ 'User:read', 'UserAccount:read', 'UserCollection:read', 'UserPublic:read', 'UserAccount:update' ,'User:write' ]
        firstName:
            groups: [ 'User:read', 'UserAccount:read', 'UserCollection:read', 'UserPublic:read', 'UserAccount:update' ,'User:write', 'BlogPost:read' ]
        lastName:
            groups: [ 'User:read', 'UserAccount:read', 'UserCollection:read', 'UserPublic:read', 'UserAccount:update' ,'User:write', 'BlogPost:read' ]
        middleName:
            groups: [ 'User:read', 'UserAccount:read', 'UserCollection:read', 'UserPublic:read', 'UserAccount:update' ,'User:write' ]
        gender:
            groups: [ 'User:read', 'UserAccount:read', 'UserCollection:read', 'UserPublic:read', 'UserAccount:update' ,'User:write', 'BlogPost:read' ]
        birthYear:
            groups: [ 'User:read', 'UserAccount:read', 'UserCollection:read', 'User:update' ,'UserAccount:write' ]
        displayName:
            groups: [ 'User:read', 'UserAccount:read', 'UserCollection:read', 'User:update' ,'User:write' ]
        jobTitle:
            groups: [ 'User:read', 'UserAccount:read', 'UserCollection:read', 'UserAccount:update' ,'User:write', 'BlogPost:read' ]
        description:
            groups: [ 'User:read', 'UserAccount:read', 'UserCollection:read', 'UserAccount:update' ,'User:write', 'BlogPost:read' ]
        customerNumber:
            groups: [ 'User:read', 'UserAccount:read', 'UserCollection:read', 'User:update' ]
        status:
            groups: [ 'User:read', 'UserAccount:read', 'UserCollection:read', 'User:update' ]
        country:
            groups: [ 'User:read', 'UserAccount:read', 'UserCollection:read', 'UserAccount:update' ,'User:write' ]
        createdAt:
            groups: ['User:read', 'UserCollection:read']
        createdBy:
            groups: ['User:read', 'UserCollection:read', 'User:write']
        updatedAt:
            groups: [ 'User:read', 'UserCollection:read']
        updatedBy:
            groups: ['User:read', 'UserCollection:read', 'User:update', 'UserAccount:update']
