<?php

declare(strict_types=1);

namespace App\DataFixtures;

use App\Factory\CountryFactory;
use App\Factory\RegionFactory;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Bundle\FixturesBundle\FixtureGroupInterface;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\Persistence\ObjectManager;
use Faker\Factory;

class CountryFixtures extends Fixture implements DependentFixtureInterface, FixtureGroupInterface
{
    /**
     * @var array<int, mixed>
     */
    private array $countries = [
        [
            'id' => 'AG',
            'name' => 'Antigua and Barbuda',
            'regionId' => 'CARIBBEAN',
            'active' => true,
            'sortOrder' => 9,
        ],
        [
            'id' => 'AR',
            'name' => 'Argentina',
            'regionId' => 'SOUTH_AMERICA',
            'active' => true,
            'sortOrder' => 10,
        ],
        [
            'id' => 'AW',
            'name' => 'Aruba',
            'regionId' => 'CARIBBEAN',
            'active' => true,
            'sortOrder' => 12,
        ],
        [
            'id' => 'AU',
            'name' => 'Australia',
            'regionId' => 'OCEANIA',
            'active' => true,
            'sortOrder' => 13,
        ],
        [
            'id' => 'AT',
            'name' => 'Austria',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 14,
        ],
        [
            'id' => 'BS',
            'name' => 'Bahamas',
            'regionId' => 'CARIBBEAN',
            'active' => true,
            'sortOrder' => 16,
        ],
        [
            'id' => 'BH',
            'name' => 'Bahrain',
            'regionId' => 'MIDDLE_EAST',
            'active' => true,
            'sortOrder' => 17,
        ],
        [
            'id' => 'BB',
            'name' => 'Barbados',
            'regionId' => 'CARIBBEAN',
            'active' => true,
            'sortOrder' => 19,
        ],
        [
            'id' => 'BY',
            'name' => 'Belarus',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 20,
        ],
        [
            'id' => 'BE',
            'name' => 'Belgium',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 21,
        ],
        [
            'id' => 'BZ',
            'name' => 'Belize',
            'regionId' => 'CENTRAL_AMERICA',
            'active' => true,
            'sortOrder' => 22,
        ],
        [
            'id' => 'BM',
            'name' => 'Bermuda',
            'regionId' => 'CARIBBEAN',
            'active' => true,
            'sortOrder' => 24,
        ],
        [
            'id' => 'BO',
            'name' => 'Bolivia',
            'regionId' => 'SOUTH_AMERICA',
            'active' => true,
            'sortOrder' => 26,
        ],
        [
            'id' => 'BA',
            'name' => 'Bosnia and Herzegovina',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 28,
        ],
        [
            'id' => 'BW',
            'name' => 'Botswana',
            'regionId' => 'AFRICA',
            'active' => true,
            'sortOrder' => 29,
        ],
        [
            'id' => 'BV',
            'name' => 'Bouvet Island',
            'regionId' => 'ANTARCTICA',
            'active' => true,
            'sortOrder' => 30,
        ],
        [
            'id' => 'BR',
            'name' => 'Brazil',
            'regionId' => 'SOUTH_AMERICA',
            'active' => true,
            'sortOrder' => 31,
        ],
        [
            'id' => 'BG',
            'name' => 'Bulgaria',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 45,
        ],
        [
            'id' => 'CA',
            'name' => 'Canada',
            'regionId' => 'NORTH_AMERICA',
            'active' => true,
            'sortOrder' => 50,
        ],
        [
            'id' => 'KY',
            'name' => 'Cayman Islands',
            'regionId' => 'CARIBBEAN',
            'active' => true,
            'sortOrder' => 52,
        ],
        [
            'id' => 'CL',
            'name' => 'Chile',
            'regionId' => 'SOUTH_AMERICA',
            'active' => true,
            'sortOrder' => 55,
        ],
        [
            'id' => 'CN',
            'name' => 'China',
            'regionId' => 'ASIA',
            'active' => true,
            'sortOrder' => 56,
        ],
        [
            'id' => 'CX',
            'name' => 'Christmas Island',
            'regionId' => 'OCEANIA',
            'active' => true,
            'sortOrder' => 57,
        ],
        [
            'id' => 'CC',
            'name' => 'Cocos (Keeling) Islands',
            'regionId' => 'OCEANIA',
            'active' => true,
            'sortOrder' => 58,
        ],
        [
            'id' => 'CO',
            'name' => 'Colombia',
            'regionId' => 'SOUTH_AMERICA',
            'active' => true,
            'sortOrder' => 59,
        ],
        [
            'id' => 'CK',
            'name' => 'Cook Islands',
            'regionId' => 'OCEANIA',
            'active' => true,
            'sortOrder' => 63,
        ],
        [
            'id' => 'CR',
            'name' => 'Costa Rica',
            'regionId' => 'CENTRAL_AMERICA',
            'active' => true,
            'sortOrder' => 64,
        ],
        [
            'id' => 'HR',
            'name' => 'Croatia',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 66,
        ],
        [
            'id' => 'CU',
            'name' => 'Cuba',
            'regionId' => 'CARIBBEAN',
            'active' => true,
            'sortOrder' => 67,
        ],
        [
            'id' => 'CY',
            'name' => 'Cyprus',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 69,
        ],
        [
            'id' => 'CZ',
            'name' => 'Czech Republic',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 70,
        ],
        [
            'id' => 'DK',
            'name' => 'Denmark',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 71,
        ],
        [
            'id' => 'DO',
            'name' => 'Dominican Republic',
            'regionId' => 'CARIBBEAN',
            'active' => true,
            'sortOrder' => 74,
        ],
        [
            'id' => 'EC',
            'name' => 'Ecuador',
            'regionId' => 'SOUTH_AMERICA',
            'active' => true,
            'sortOrder' => 76,
        ],
        [
            'id' => 'EG',
            'name' => 'Egypt',
            'regionId' => 'MIDDLE_EAST',
            'active' => true,
            'sortOrder' => 77,
        ],
        [
            'id' => 'EE',
            'name' => 'Estonia',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 81,
        ],
        [
            'id' => 'FO',
            'name' => 'Faroe Islands',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 84,
        ],
        [
            'id' => 'FJ',
            'name' => 'Fiji',
            'regionId' => 'OCEANIA',
            'active' => true,
            'sortOrder' => 85,
        ],
        [
            'id' => 'FI',
            'name' => 'Finland',
            'regionId' => 'EUROPE',
            'capital' => 'Helsinki',
            'active' => true,
            'sortOrder' => 86,
        ],
        [
            'id' => 'FR',
            'name' => 'France',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 87,
        ],
        [
            'id' => 'PF',
            'name' => 'French Polynesia',
            'regionId' => 'OCEANIA',
            'active' => true,
            'sortOrder' => 89,
        ],
        [
            'id' => 'TF',
            'name' => 'French Southern Territories',
            'regionId' => 'ANTARCTICA',
            'active' => true,
            'sortOrder' => 90,
        ],
        [
            'id' => 'DE',
            'name' => 'Germany',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 94,
        ],
        [
            'id' => 'GI',
            'name' => 'Gibraltar',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 96,
        ],
        [
            'id' => 'GR',
            'name' => 'Greece',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 97,
        ],
        [
            'id' => 'GL',
            'name' => 'Greenland',
            'regionId' => 'NORTH_AMERICA',
            'active' => true,
            'sortOrder' => 98,
        ],
        [
            'id' => 'GD',
            'name' => 'Grenada',
            'regionId' => 'CARIBBEAN',
            'active' => true,
            'sortOrder' => 99,
        ],
        [
            'id' => 'GU',
            'name' => 'Guam',
            'regionId' => 'OCEANIA',
            'active' => true,
            'sortOrder' => 101,
        ],
        [
            'id' => 'GT',
            'name' => 'Guatemala',
            'regionId' => 'CENTRAL_AMERICA',
            'capital' => 'Guatemala City',
            'active' => true,
            'sortOrder' => 102,
        ],
        [
            'id' => 'GG',
            'name' => 'Guernsey',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 103,
        ],
        [
            'id' => 'HN',
            'name' => 'Honduras',
            'regionId' => 'CENTRAL_AMERICA',
            'active' => true,
            'sortOrder' => 109,
        ],
        [
            'id' => 'HK',
            'name' => 'Hong Kong',
            'regionId' => 'ASIA',
            'active' => true,
            'sortOrder' => 110,
        ],
        [
            'id' => 'HU',
            'name' => 'Hungary',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 111,
        ],
        [
            'id' => 'IS',
            'name' => 'Iceland',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 112,
        ],
        [
            'id' => 'IN',
            'name' => 'India',
            'regionId' => 'ASIA',
            'active' => true,
            'sortOrder' => 113,
        ],
        [
            'id' => 'ID',
            'name' => 'Indonesia',
            'regionId' => 'ASIA',
            'active' => true,
            'sortOrder' => 114,
        ],
        [
            'id' => 'IE',
            'name' => 'Ireland',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 117,
        ],
        [
            'id' => 'IM',
            'name' => 'Isle of Man',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 118,
        ],
        [
            'id' => 'IT',
            'name' => 'Italy',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 120,
        ],
        [
            'id' => 'JM',
            'name' => 'Jamaica',
            'regionId' => 'CARIBBEAN',
            'active' => true,
            'sortOrder' => 121,
        ],
        [
            'id' => 'JP',
            'name' => 'Japan',
            'regionId' => 'ASIA',
            'active' => true,
            'sortOrder' => 122,
        ],
        [
            'id' => 'JE',
            'name' => 'Jersey',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 123,
        ],
        [
            'id' => 'JO',
            'name' => 'Jordan',
            'regionId' => 'MIDDLE_EAST',
            'active' => true,
            'sortOrder' => 124,
        ],
        [
            'id' => 'KE',
            'name' => 'Kenya',
            'regionId' => 'AFRICA',
            'active' => true,
            'sortOrder' => 126,
        ],
        [
            'id' => 'KW',
            'name' => 'Kuwait',
            'regionId' => 'MIDDLE_EAST',
            'active' => true,
            'sortOrder' => 128,
        ],
        [
            'id' => 'LV',
            'name' => 'Latvia',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 131,
        ],
        [
            'id' => 'LB',
            'name' => 'Lebanon',
            'regionId' => 'MIDDLE_EAST',
            'active' => true,
            'sortOrder' => 132,
        ],
        [
            'id' => 'LI',
            'name' => 'Liechtenstein',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 136,
        ],
        [
            'id' => 'LT',
            'name' => 'Lithuania',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 137,
        ],
        [
            'id' => 'LU',
            'name' => 'Luxembourg',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 138,
        ],
        [
            'id' => 'MK',
            'name' => 'Macedonia, Republic of',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 140,
        ],
        [
            'id' => 'MY',
            'name' => 'Malaysia',
            'regionId' => 'ASIA',
            'active' => true,
            'sortOrder' => 143,
        ],
        [
            'id' => 'MV',
            'name' => 'Maldives',
            'capital' => 'Malé',
            'regionId' => 'AFRICA',
            'active' => true,
            'sortOrder' => 144,
        ],
        [
            'id' => 'MT',
            'name' => 'Malta',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 146,
        ],
        [
            'id' => 'MQ',
            'name' => 'Martinique',
            'regionId' => 'CARIBBEAN',
            'active' => true,
            'sortOrder' => 148,
        ],
        [
            'id' => 'MU',
            'name' => 'Mauritius',
            'regionId' => 'AFRICA',
            'active' => true,
            'sortOrder' => 150,
        ],
        [
            'id' => 'MX',
            'name' => 'Mexico',
            'regionId' => 'NORTH_AMERICA',
            'active' => true,
            'sortOrder' => 152,
        ],
        [
            'id' => 'MD',
            'name' => 'Moldova, Republic of',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 154,
        ],
        [
            'id' => 'MC',
            'name' => 'Monaco',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 155,
        ],
        [
            'id' => 'ME',
            'name' => 'Montenegro',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 157,
        ],
        [
            'id' => 'MS',
            'name' => 'Montserrat',
            'regionId' => 'CARIBBEAN',
            'active' => true,
            'sortOrder' => 158,
        ],
        [
            'id' => 'MA',
            'name' => 'Morocco',
            'regionId' => 'AFRICA',
            'active' => true,
            'sortOrder' => 159,
        ],
        [
            'id' => 'NP',
            'name' => 'Nepal',
            'regionId' => 'ASIA',
            'active' => true,
            'sortOrder' => 164,
        ],
        [
            'id' => 'NL',
            'name' => 'Netherlands',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 165,
        ],
        [
            'id' => 'NZ',
            'name' => 'New Zealand',
            'regionId' => 'OCEANIA',
            'active' => true,
            'sortOrder' => 167,
        ],
        [
            'id' => 'NI',
            'name' => 'Nicaragua',
            'regionId' => 'CENTRAL_AMERICA',
            'active' => true,
            'sortOrder' => 168,
        ],
        [
            'id' => 'NO',
            'name' => 'Norway',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 175,
        ],
        [
            'id' => 'OM',
            'name' => 'Oman',
            'regionId' => 'MIDDLE_EAST',
            'active' => true,
            'sortOrder' => 176,
        ],
        [
            'id' => 'PK',
            'name' => 'Pakistan',
            'regionId' => 'ASIA',
            'active' => true,
            'sortOrder' => 177,
        ],
        [
            'id' => 'PA',
            'name' => 'Panama',
            'regionId' => 'CENTRAL_AMERICA',
            'active' => true,
            'sortOrder' => 180,
        ],
        [
            'id' => 'PG',
            'name' => 'Papua New Guinea',
            'regionId' => 'OCEANIA',
            'active' => true,
            'sortOrder' => 181,
        ],
        [
            'id' => 'PY',
            'name' => 'Paraguay',
            'regionId' => 'SOUTH_AMERICA',
            'active' => true,
            'sortOrder' => 182,
        ],
        [
            'id' => 'PE',
            'name' => 'Peru',
            'regionId' => 'SOUTH_AMERICA',
            'active' => true,
            'sortOrder' => 183,
        ],
        [
            'id' => 'PL',
            'name' => 'Poland',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 186,
        ],
        [
            'id' => 'PT',
            'name' => 'Portugal',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 187,
        ],
        [
            'id' => 'PR',
            'name' => 'Puerto Rico',
            'regionId' => 'CARIBBEAN',
            'active' => true,
            'sortOrder' => 188,
        ],
        [
            'id' => 'QA',
            'name' => 'Qatar',
            'regionId' => 'MIDDLE_EAST',
            'active' => true,
            'sortOrder' => 189,
        ],
        [
            'id' => 'RO',
            'name' => 'Romania',
            'regionId' => 'EUROPE',
            'capital' => 'Bucharest',
            'active' => true,
            'sortOrder' => 192,
        ],
        [
            'id' => 'RU',
            'name' => 'Russia',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 193,
        ],
        [
            'id' => 'KN',
            'name' => 'Saint Kitts and Nevis',
            'regionId' => 'CARIBBEAN',
            'active' => true,
            'sortOrder' => 197,
        ],
        [
            'id' => 'LC',
            'name' => 'Saint Kitts and Nevis',
            'regionId' => 'CARIBBEAN',
            'active' => true,
            'sortOrder' => 198,
        ],
        [
            'id' => 'VC',
            'name' => 'Saint Vincent and the Grenadines',
            'regionId' => 'CARIBBEAN',
            'active' => true,
            'sortOrder' => 201,
        ],
        [
            'id' => 'WS',
            'name' => 'Samoa',
            'regionId' => 'OCEANIA',
            'active' => true,
            'sortOrder' => 202,
        ],
        [
            'id' => 'SM',
            'name' => 'San Marino',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 203,
        ],
        [
            'id' => 'SA',
            'name' => 'Saudi Arabia',
            'regionId' => 'MIDDLE_EAST',
            'active' => true,
            'sortOrder' => 205,
        ],
        [
            'id' => 'RS',
            'name' => 'Serbia',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 207,
        ],
        [
            'id' => 'SC',
            'name' => 'Seychelles',
            'regionId' => 'AFRICA',
            'active' => true,
            'sortOrder' => 208,
        ],
        [
            'id' => 'SG',
            'name' => 'Singapore',
            'regionId' => 'ASIA',
            'active' => true,
            'sortOrder' => 210,
        ],
        [
            'id' => 'SX',
            'name' => 'Saint Martin',
            'regionId' => 'CARIBBEAN',
            'active' => true,
            'sortOrder' => 211,
        ],
        [
            'id' => 'SK',
            'name' => 'Slovakia',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 212,
        ],
        [
            'id' => 'SI',
            'name' => 'Slovenia',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 213,
        ],
        [
            'id' => 'SB',
            'name' => 'Solomon Islands',
            'regionId' => 'OCEANIA',
            'active' => true,
            'sortOrder' => 214,
        ],
        [
            'id' => 'ZA',
            'name' => 'South Africa',
            'regionId' => 'AFRICA',
            'active' => true,
            'sortOrder' => 216,
        ],
        [
            'id' => 'GS',
            'name' => 'South Georgia and the South Sandwich Islands',
            'regionId' => 'ANTARCTICA',
            'active' => true,
            'sortOrder' => 217,
        ],
        [
            'id' => 'KR',
            'name' => 'South Korea',
            'regionId' => 'ASIA',
            'active' => true,
            'sortOrder' => 218,
        ],
        [
            'id' => 'ES',
            'name' => 'Spain',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 220,
        ],
        [
            'id' => 'SJ',
            'name' => 'Svalbard and Jan Mayen',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 224,
        ],
        [
            'id' => 'SE',
            'name' => 'Sweden',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 226,
        ],
        [
            'id' => 'CH',
            'name' => 'Switzerland',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 227,
        ],
        [
            'id' => 'TW',
            'name' => 'Taiwan',
            'regionId' => 'ASIA',
            'active' => true,
            'sortOrder' => 229,
        ],
        [
            'id' => 'TZ',
            'name' => 'Tanzania',
            'regionId' => 'AFRICA',
            'active' => true,
            'sortOrder' => 231,
        ],
        [
            'id' => 'TH',
            'name' => 'Thailand',
            'regionId' => 'ASIA',
            'active' => true,
            'sortOrder' => 232,
        ],
        [
            'id' => 'TO',
            'name' => 'Tonga',
            'regionId' => 'OCEANIA',
            'active' => true,
            'sortOrder' => 235,
        ],
        [
            'id' => 'TT',
            'name' => 'Trinidad and Tobago',
            'regionId' => 'CARIBBEAN',
            'active' => true,
            'sortOrder' => 236,
        ],
        [
            'id' => 'TN',
            'name' => 'Tunisia',
            'regionId' => 'AFRICA',
            'active' => true,
            'sortOrder' => 237,
        ],
        [
            'id' => 'TR',
            'name' => 'Turkey',
            'regionId' => 'ASIA',
            'active' => true,
            'sortOrder' => 238,
        ],
        [
            'id' => 'TC',
            'name' => 'Turks and Caicos Islands',
            'regionId' => 'CARIBBEAN',
            'active' => true,
            'sortOrder' => 240,
        ],
        [
            'id' => 'UA',
            'name' => 'Ukraine',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 243,
        ],
        [
            'id' => 'AE',
            'name' => 'United Arab Emirates',
            'regionId' => 'MIDDLE_EAST',
            'active' => true,
            'sortOrder' => 244,
        ],
        [
            'id' => 'GB',
            'name' => 'United Kingdom',
            'regionId' => 'EUROPE',
            'active' => true,
            'sortOrder' => 245,
        ],
        [
            'id' => 'US',
            'name' => 'United States',
            'regionId' => 'NORTH_AMERICA',
            'active' => true,
            'sortOrder' => 246,
        ],
        [
            'id' => 'UY',
            'name' => 'Uruguay',
            'regionId' => 'SOUTH_AMERICA',
            'active' => true,
            'sortOrder' => 247,
        ],
        [
            'id' => 'VE',
            'name' => 'Venezuela',
            'regionId' => 'SOUTH_AMERICA',
            'active' => true,
            'sortOrder' => 250,
        ],
        [
            'id' => 'VN',
            'name' => 'Vietnam',
            'regionId' => 'ASIA',
            'active' => true,
            'sortOrder' => 251,
        ],
        [
            'id' => 'ZM',
            'name' => 'Zambia',
            'regionId' => 'AFRICA',
            'active' => true,
            'sortOrder' => 255,
        ],
        [
            'id' => 'ZW',
            'name' => 'Zimbabwe',
            'regionId' => 'AFRICA',
            'active' => true,
            'sortOrder' => 256,
        ],
    ];

    public function getDependencies(): array
    {
        return [
            RegionFixtures::class,
        ];
    }

    public static function getGroups(): array
    {
        return ['country', 'user', 'place', 'all'];
    }

    public function load(ObjectManager $manager): void
    {
        $faker = Factory::create();

        CountryFactory::createSequence(
            function () use ($faker) {
                foreach ($this->countries as $country) {
                    yield [
                        'id' => $country['id'],
                        'name' => $country['name'],
                        'active' => $country['active'],
                        'sortOrder' => $country['sortOrder'],
                        'createdBy' => 'SYSTEM',
                        'createdAt' => $faker->dateTimeInInterval('- 1 year', '+ 0 day'),
                        'region' => RegionFactory::find(['id' => $country['regionId']]),
                    ];
                }
            }
        );
    }
}
